[build]
  command = "npm run build"
  publish = "dist/rem-to-pixel/browser"  # Changed from dist/rem-to-pixel

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200