[build]
  command = "ng build --configuration production"
  publish = "dist/rem-to-pixel/browser"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"