[build]
  command = "npm run build-prod"
  publish = "dist/rem-to-pixel/browser"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200